'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    const groups = await queryInterface.sequelize.query(
      'SELECT id from "Groups" ORDER BY id;'
    );
    const groupRows = groups[0]
    const venues = await queryInterface.sequelize.query(
      'SELECT id from "Venues" ORDER BY id;'
    );
    const venueRows = venues[0]
    await queryInterface.bulkInsert('Events', [

      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Paint a Pet Portrait',
        type: 'In Person',
        capacity: 20,
        price: 10,
        description: 'Paint a Pet Portrait at the Barking Dog ..Dogs Welcome! It is EASY No Artistic Background Necessary One of NYC BEST DOG FRIENDLY ACTIVITIES Artist Draws your Pet for you! Trace and Paint watercolor portraits of your pet. It will be pre sketched and ready for you to trace and watercolor your own masterpiece.',
        startDate: new Date('2022-08-09 10:00:00'),
        endDate: new Date('2022-08-09 14:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Eskie Gathering 2022',
        type: 'In Person',
        capacity: 50,
        price: 0,
        description: 'Come join Eskies of New York City (find us on facebook) for a special meetup at the Tennis Center in Central Park for a bring your own picnic and 1.6 mi walk around the reservoir with your leashed Eskies, other pups from a Spitz family as part of the international Great Global Greyhound Walk 2022!',
        startDate: new Date('2022-08-03 11:00:00'),
        endDate: new Date('2022-08-03 17:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: venueRows[0].id,
        name: 'Tennis Single',
        type: 'In Person',
        startDate: new Date('2021-11-12 20:00:00'),
        previewImage: 'image url',
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
      {
        groupId: groupRows[0].id,
        venueId: null,
        name: 'Gantry park dog walk',
        type: 'In Person',
        capacity: 20,
        price: 0,
        description: 'Take a leisurely walk around Brookdale Park with our pups. Meet in Astoria Park, walk the pooches and find a place to grab a drink if we want. I will be contacting RVSPs individually the day prior to even to confirm you are be coming!',
        startDate: new Date('2022-08-19 12:00:00'),
        endDate: new Date('2022-08-19 19:00:00'),
        previewImage: null,
      },
    ], {});
  },
  async down(queryInterface, Sequelize) {
    const Op = Sequelize.Op;
    await queryInterface.bulkDelete('Events', null, {});
  },
};
